export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USERSLISTS='GET_USERSLISTS'
export const  GET_PENDINGLIST=' GET_PENDINGLIST';
export const GET_TASKAPPROVEDLIST='GET_TASKAPPROVEDLIST';
export const GET_TASKREJECTEDLIST='GET_TASKREJECTEDLIST';
export const GET_DEPARTMENTPENDINGLIST='GET_DEPARTMENTPENDINGLIST';

